ApplicationDataPortal/Controllers/API/DisplayTypesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ApplicationDataPortal.Core;
using ApplicationDataPortal.Core.Dtos;
using ApplicationDataPortal.Core.Models;
using ApplicationDataPortal.Persistence;
using ApplicationDataPortal.Repositories;
using AutoMapper;

namespace ApplicationDataPortal.Controllers.API
{
    public class DisplayTypesController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;

        public DisplayTypesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //Get /api/DisplayTypes
        public IHttpActionResult GetDisplayTypes()
        {
            var display = _unitOfWork.DisplayTypes.GetDisplayTypes()
                .Select(Mapper.Map<DisplayTypes, DisplayTypeDto>);

            return Ok(display);
        }

        
        //Get /api/DisplayTypes/1
        public IHttpActionResult GetDisplayType(int Id)
        {
            var result = _unitOfWork.DisplayTypes.GetDisplayType(Id);

            if (result == null)
            {
                return BadRequest("Display Type Does Not Exist");
            }

            return Ok(result);
        }
        
        //Post /api/DisplayTypes/
        [HttpPost]
        public void CreateDisplayType(DisplayTypeDto displayTypeDto)
        {
            _unitOfWork.DisplayTypes.CreateDisplayType(displayTypeDto);
            _unitOfWork.Complete();
        }


        //Put /api/displaytypes/1 
        [HttpPut]
        public IHttpActionResult UpdateDisplayType(int Id, DisplayTypeDto displayTypeDto)
        {
            var displayTypeInDB = _unitOfWork.DisplayTypes.GetDisplayType(Id);

            if (displayTypeInDB == null)
            {
                return BadRequest("That Display Type doesn't exist");
            }

            _unitOfWork.DisplayTypes.UpdateDisplayType(displayTypeDto,displayTypeInDB);
            _unitOfWork.Complete();
            return Ok();
        }

        [HttpDelete]
        public IHttpActionResult DeleteDisplayType(int Id)
        {
            var displayTypeInDb = _unitOfWork.DisplayTypes.GetDisplayType(Id);
            var attachedPromotions = _unitOfWork.Promotions.GetNumberOfPromotionsOnDisplayType(Id);

            if (displayTypeInDb == null)
            {
                return BadRequest("Display Type not found");
            }

            if (attachedPromotions > 0)
            {
                return BadRequest("Dislay Type Used in promotions");
            }

            _unitOfWork.DisplayTypes.DeleteDisplayType(Id);
            _unitOfWork.Complete();

            return Ok();
        }
    }
}

ApplicationDataPortal/Controllers/DisplayTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ApplicationDataPortal.Core.Models.AccountModels;

namespace ApplicationDataPortal.Controllers
{
    public class DisplayTypesController : Controller
    {

        private ApplicationDbContext _context;

        public DisplayTypesController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }



        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult New()
        {
            return View();
        }
    }
}

ApplicationDataPortal/Views/DisplayTypes/Index.cshtml
<!--model List<ApplicationDataPortal.Models.DisplayTypes>-->

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div ng-controller="displayTypeController">
    <h1> Display Type Manager </h1>

    <div style="padding-bottom: 20px;">
        @Html.ActionLink("Add", "New", "DisplayTypes", new { @class ="btn btn-primary"})
    </div>

    <table id="displayTypes" style="width: 100%" class="table table-striped table-hover ">
        <thead>
        <tr>
            <th> Display Type </th>
            <th> Customer </th>
            <th> Delete Display Type </th>
            <th> Global Display Type Ref</th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<script src="~/ClientApp/controllers/displayTypeTableBuilder.js"></script>

ApplicationDataPortal/Views/DisplayTypes/New.cshtml
@model dynamic

@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2> New Display Type </h2>

<form id="newDisplayTypes">
    <div class="form-group">
        <div class="tt-container">
            <label> Name </label>
        </div>
        <input id="name" required type="text" name="name" class="form-control"/>
    </div>
    
    <div class="form-group">
        <div class="tt-container">
            <label> Customer </label>
        </div>
        <input id="customer" required type="text" name="customer" class="form-control"/>
    </div>
    
    <div class="form-group">
        <div class="tt-container">
            <label> Global Display Type Ref </label>
        </div>
        <select id="globalDisplayTypeRef" name="globalDisplayTypeRef" class="form-control">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>
    </div>
    
    <button id="submit" class="btn btn-primary">Submit</button>

</form>

@section scripts {
    
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function() {
            var vm = {}


            var customers = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url: '/api/customers?query=%QUERY',
                    wildcard: '%QUERY'
                }
            });
            $('#customer').typeahead({
                    highlight: true
                },
                {
                    name: 'customers',
                    display: 'name',
                    source: customers
                }).on("typeahead:select",
                function(e, customer) {
                    vm.customerId = customer.id;
                    console.log(vm);
                });

            $("#newDisplayTypes").submit(function(e) {
                vm.description = $('input[name=name]').val();
                vm.globalDisplayTypeRef = parseInt($('#globalDisplayTypeRef').find(":selected").val());
                console.log(vm);
                $.ajax({
                        url: '/api/DisplayTypes',
                        type: 'POST',
                        data: vm
                    })
                    .done(function() {
                        toastr.success("Successfully Posted Display Type");
                        $("#customer").typeahead("val", "");
                        $("#name").val('');
                        $(location).attr('href', '/DisplayTypes');
                    })
                    .fail(function() {
                        toastr.error("Failed to post display type");
                    });
                event.preventDefault();
            });


        });
    </script>
}